#Help Command
Help-Command:
  - "Translate Comamnd"
  - " Usage: /translate <language from> <language to> <content>"
  - " You can use AUTO in language from for Google to attempt to find the language of the content."

#Reload Command
Reload-Command:
  - "Translate Configuration File has been reloaded!"

#Translate Command
Translate-Command:
  - "&cFROM: %from-language% - %original-content%"
  - "&aTO: %to-language% - %translated-content%"
