name: Translate
description: Translate messages in-game using Google Translate's REST APIs.
version: 1.0-SNAPSHOT
website: https://www.mc-market.org/members/53967/
author: ThatKawaiiSam
main: io.github.thatkawaiisam.translate.TranslatePlugin